THEME_NEW/config/routes.rb
Rails.application.routes.draw do
  
  
get "pages/index"
get "pages/about"
get "pages/contact"
get "pages/features"
get "pages/login"
get "pages/pricing"
get "pages/register"

root :to => 'pages#index'

end

THEME_NEW/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

THEME_NEW/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

THEME_NEW/app/helpers/application_helper.rb
module ApplicationHelper
end

THEME_NEW/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Safety Management System</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <%= stylesheet_link_tag  "application", "bootstrap", "bootstrap-responsive", "font", "font-awesome", "base.css", "blue.css"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="img/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" href="<%= asset_path('img/favicon.ico')%>">
</head>
<body>
	<BR>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-primary btn-dropnav" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> 
    	<span class="icon-bar"></span> <span class="icon-bar"></span> </a>
    	 <a class="brand" href=<%= root_path %>>
    	 	<img src="<%= asset_path('img/logo2n.png')%>" alt="" border="0">
    	 </a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><a href="<%= root_path %>">Главная</a></li>
          <li><a href="<%= pages_about_path %>">О нас</a></li>
          <li><a href="<%= pages_features_path %>">Особенности</a></li>
          <li><a href="<%= pages_pricing_path %>">Цены</a></li>
          <li><a href="<%= pages_login_path %>">Вход</a></li>
          <li><a href="<%= pages_register_path %>">Регистрация</a></li>
          <li><a href="<%= pages_contact_path %>">Контакты</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<br>
<%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    $(".js-video").fitVids();
      $("#totop").click(function () {
    $("body, html").animate({
      scrollTop: 0
      }, 300);
    return false;
    }); 
  });
  </script>
</body>
</html>

THEME_NEW/app/views/pages/about.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>О нас</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span6">
        <h2>Наша цель</h2>
        <p>Целью оценки и управления профессиональными рисками является обеспечение безопасности
        	 и сохранение здоровья работника в процессе трудовой деятельности</p>
      </div>
      <div class="span6">
        <h2>Главное</h2>
        <p>Управление профессиональными рисками - комплекс взаимосвязанных мероприятий, включающих в себя меры по выявлению,
        	 оценке и снижению уровней профессиональных рисков</p>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <h2 class="txt-middle">Наша команда</h2>
        <hr class="dashed">
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <ul class="thumbnails">
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Наши ссылки</h3>
        <ul>
          <li><a href="<%= root_path %>">Главная</a></li>
          <li><a href="<%= pages_about_path %>">О нас</a></li>
          <li><a href="<%= pages_features_path %>">Особенности</a></li>
          <li><a href="<%= pages_pricing_path %>">Цены</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Наши правила</h3>
        <ul>
          <li><a href="#">Политики безопасности</a></li>
          <li><a href="#">Правила пользования</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Блоги</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Safety Management System <span id="totop" class="pull-right">Наверх</span></p>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/contact.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Наши контакты</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span5">
        <h2><i class="icon-envelope"></i>       Написать нам</h2>
        <fieldset>
        <div class="control-group">
          <div class="controls">
            <input class="span5" type="text" placeholder="Ваше полное имя">
          </div>
          <div class="controls">
            <input class="span5" type="text" placeholder="Ваш Email">
          </div>
          <div class="controls">
            <input class="span5" type="text" placeholder="Тема сообщения">
          </div>
          <div class="controls">
            <textarea class="span5" id="textarea" rows="6" placeholder="Сообщение"></textarea>
          </div>
          <button class="btn btn-primary">Отправить письмо</button>
        </div>
        </fieldset>
      </div>
      <div class="span7">
        <div class="row">
          <div class="span3">
            <h2><i class="icon-map-marker"></i> Адрес</h2>
            <address>
            MD/ Chisinau  <br>
            str Petru Rares 77, of 67 
            </address>
          </div>
          <div class="span4">
            <h2><i class="icon-phone"></i> Телефон</h2>
            <address>
            Тел.: (123) 456-7890 <br>
            Факс.: (123) 456-7890
            </address>
          </div>
        </div>
        <div> <img border="0" alt="" src="http://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=14&size=840x230&maptype=roadmap&sensor=false"> </div>
      </div>
    </div>
    <hr class="space">
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Наши ссылки</h3>
        <ul>
          <li><a href="<%= root_path %>">Главная</a></li>
          <li><a href="<%= pages_about_path %>">О нас</a></li>
          <li><a href="<%= pages_features_path %>">Особенности</a></li>
          <li><a href="<%= pages_pricing_path %>">Цены</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Наши правила</h3>
        <ul>
          <li><a href="#">Политики безопасности</a></li>
          <li><a href="#">Правила пользования</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Блоги</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Safety Management System <span id="totop" class="pull-right">Наверх</span></p>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/features.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Особенности</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
    </div>
    <hr class="dashed">
    <div class="row">
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div class="callout well">
          <h2>Try our service free for 30 days</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipiscing elit arcu massa, vehicula in felis.</p>
          <a href="#" class="btn btn-primary btn-action">Get Started Now <i class="icon-arrow-right"></i></a> </div>
      </div>
    </div>
    <hr class="space">
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/index.html.erb
<div id="landing">
  <div class="container">
    <div class="row">
      <div class="span5">
        <h1>Оценка рисков<br>
        	на рабочих местах </h1>
        <p> Определение фактических значений вредных и (или) опасных производственных факторов (физические, химические и биологические) 
        	тяжести и (или) напряженности трудового процесса на рабочих местах; </p>
        <p><a href="#" class="btn btn-primary btn-action">Вход</a></p>
      </div>
      <div class="span7">
        <div class="js-video">
        	<BR>
          <iframe src="http://player.vimeo.com/video/69425511?title=0&amp;byline=0&amp;portrait=0&amp;badge=0" 
          width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row main-tab">
      <div class="span4 bouncy">
      <div class="divider">
        <div class="icon_wrapper"> <i class="icon-comments"></i> </div>
        <h2>Интересно</h2>
        <p>Первым, значительным по объему и содержанию, документом ЕС, 
        	представляющем развернутые рекомендации по вопросам оценки профессионального риска,  
        	было «Руководство по оценке риска на работе»</p>
        </div>
      </div>
      <div class="span4 bouncy">
      <div class="divider">
        <div class="icon_wrapper"> <i class="icon-delicious-sign"></i> </div>
        <h2>Эффективность</h2>
        <p>Страховой тариф назначается страховщиком по результатам проведения оценки профессиональных рисков
        	на предприятии. Его размер напрямую зависит от степени опасности для пресонала деятельности предприятия.</p>
        </div>
      </div>
      <div class="span4 bouncy">
      <div class="divider last">
        <div class="icon_wrapper"> <i class="icon-paste"></i> </div>
        <h2>Финансы</h2>
        <p>Грамотная оценка профессиональных рисков — залог финансового успеха.
			Главная цель методики — вычисление опасных ситуаций, 
			оценка профессиональных рисков и определяющих их факторов, и как следствие, минимизация ваших возможных потерь.
		</p>
        </div>
      </div>
    </div>
  </div>
  <div class="featured-container">
    <div class="container">
      <div class="row">
        <h2>Сопутсвующие проекты</h2>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"></a></div>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"> </a></div>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"> </a></div>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Наши ссылки</h3>
        <ul>
          <li><a href="<%= root_path %>">Главная</a></li>
          <li><a href="<%= pages_about_path %>">О нас</a></li>
          <li><a href="<%= pages_features_path %>">Особенности</a></li>
          <li><a href="<%= pages_pricing_path %>">Цены</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Наши правила</h3>
        <ul>
          <li><a href="#">Политики безопасности</a></li>
          <li><a href="#">Правила пользования</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Блоги</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Safety Management System <span id="totop" class="pull-right">Наверх</span></p>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/login.html.erb
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="modal modal-flat">
          <div class="modal-header">
            <h3>Форма входа</h3>
          </div>
          <div class="modal-body">
            <fieldset>
            <div class="control-group">
              <div class="controls">
                <div class="input-prepend"> <span class="add-on"><i class="icon-user"></i></span>
                  <input type="text" placeholder="Username" class="span3">
                </div>
              </div>
              <div class="controls">
                <div class="input-prepend"> <span class="add-on"><i class="icon-lock"></i></span>
                  <input type="password" placeholder="Password" class="span3">
                </div>
              </div>
            </div>
            </fieldset>
            <hr class="dashed">
            <button class="btn btn-info"><i class="icon-twitter"></i> Login with Twitter</button>
            <button class="btn btn-danger"><i class="icon-google-plus"></i> Login with Google</button>
          </div>
          <div class="modal-footer">
            <button class="btn btn-warning pull-left">Forgot Your Password?</button>
            <a href="index.html" class="btn btn-primary">Log In</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/pricing.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Ценовые таблицы</h1>
      </div>
    </div>
  </div>
</div>
<div id="content" class="pricing-padding30">
  <div class="container">
    <div class="row">
      <div class="span4">
        <div class="product-plan">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Small</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$0 <small>/ на год</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Количество работников <span class="pull-right">до 20</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">5 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Поддержка <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="span4">
        <div class="product-plan popular">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Medium</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$10 <small>/ на год</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Количество работников <span class="pull-right">до 100</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">100 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Support <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="span4">
        <div class="product-plan">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Large</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$50 <small>/ на год</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Количество работников <span class="pull-right">до 500</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">500 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Support <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Наши ссылки</h3>
        <ul>
          <li><a href="<%= root_path %>">Главная</a></li>
          <li><a href="<%= pages_about_path %>">О нас</a></li>
          <li><a href="<%= pages_features_path %>">Особенности</a></li>
          <li><a href="<%= pages_pricing_path %>">Цены</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Наши правила</h3>
        <ul>
          <li><a href="#">Политики безопасности</a></li>
          <li><a href="#">Правила пользования</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Блоги</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Safety Management System <span id="totop" class="pull-right">Наверх</span></p>
      </div>
    </div>
  </div>
</div>

THEME_NEW/app/views/pages/register.html.erb
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="modal modal-flat">
          <div class="modal-header">
            <h3>Become a Bounce Member</h3>
          </div>
          <div class="modal-body">
            <button class="btn btn-info"><i class="icon-twitter"></i> Join using Twitter</button>
            <button class="btn btn-danger"><i class="icon-google-plus"></i> Join using Google</button>
            <hr class="dashed">
            <p class="text-info">create an account for free below</p>
            <fieldset>
            <div class="control-group">
              <div class="controls">
                <input type="text" placeholder="Your First Name" class="span5">
              </div>
              <div class="controls">
                <input type="text" placeholder="Your Last Name" class="span5">
              </div>
              <div class="controls">
                <input type="text" placeholder="Your Email" class="span5">
              </div>
              <div class="controls">
                <input type="password" placeholder="Password" class="span5">
              </div>
            </div>
            </fieldset>
          </div>
          <div class="modal-footer"> <a href="login.html" class="btn btn-warning pull-left">Already a Member?</a> <a href="index.html" class="btn btn-primary">Register!</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>